spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/project/{application}/{profile}
  profiles:
    active: native

management:
  security:
    enabled: false