server:
  port: 8001

spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/project/{application}/{profile}
        bootstrap: true
  profiles:
    active: native

management:
  security:
    enabled: false