server:
  port: 9003

eureka:
  instance:
    hostname: localhost
    port: 9002
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000

zuul:
  sensitiveHeaders: Cookie,Set-Cookie
  routes:
    user-server:
      path: /user/**
      serviceId: start-application
      stripPrefix: false
    oauth:
      path: /oauth/**
      serviceId: authorization-application
      stripPrefix: false