eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      dafaultZone: http://${eureka.instance.hostname:localhost}:${server.port:8761}/eureka/

spring:
  application:
    name: ms-gateway

server:
  port: ${port:8883}

management:
  endpoints:
    web:
      exposure:
        include: "*"
