server:
  port: 8883

spring:
  application:
    name: gateway-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      dafaultZone: http://${eureka.instance.hostname:localhost}:${server.port:8761}/eureka/
    instance:
      hostname: localhost

zuul:
  sensitiveHeaders: Cookie,Set-Cookie
  routes:
    user-server:
      path: /user/**
      serviceId: start-application
      stripPrefix: false
    oauth:
      path: /oauth/**
      serviceId: authorization-application
      stripPrefix: false